import java.util.Vector;


public class TestLibrary {
	private static Vector<Action> flight;
	
	public static BirdModel getModel_3x5() {
		double[][] A = new double[][]
				{{0.80, 0.05, 0.15},
				 {0.05, 0.90, 0.05},
				 {0.60, 0.10, 0.30}
				};
		
		double[][] B = new double[][]
				{{0.00, 0.50, 0.50, 0.00, 0.00},
				 {0.10, 0.10, 0.10, 0.35, 0.35},
				 {1.00, 0.00, 0.00, 0.00, 0.00}
				};
		
		double[] pi = {1.0, 0.00, 0.00};
		
		return new BirdModel(A, B, pi);
	}
	
	public static Action stringToAction(String s) {
		int birdNum = 0;
		int Haction = 0;
		int Vaction = 0;
		int movement = 0;
		
		int endIndex = s.indexOf(')');
		birdNum = Integer.parseInt(s.substring(1, endIndex));
		endIndex = s.indexOf(' ', endIndex + 1);
		char H = s.charAt(endIndex + 1);
		if(H == 'A')
			Haction = Action.ACTION_ACCELERATE;
		else if (H == 'K')
			Haction = Action.ACTION_KEEPSPEED;
		else if (H == 'S')
			Haction = Action.ACTION_STOP;
		
		endIndex = s.indexOf(' ', endIndex + 1);
		char V = s.charAt(endIndex + 1);
		if(V == 'A')
			Vaction = Action.ACTION_ACCELERATE;
		else if (V == 'K')
			Vaction = Action.ACTION_KEEPSPEED;
		else if (V == 'S')
			Vaction = Action.ACTION_STOP;
		
		endIndex = s.indexOf(' ', endIndex + 1);
		
		String moveString = s.substring(endIndex + 1);
		
		String[] motions = moveString.split("/");
		
		if(motions.length == 0)
			movement = Action.BIRD_STOPPED;
		else if (motions.length == 1) {
			if(motions[0].equals("east"))
				movement = Action.MOVE_EAST;
			else if (motions[0].equals("west"))
				movement = Action.MOVE_WEST;
		}
		else if (motions.length == 2) {
			if(motions[0].length() == 0) {
				if(motions[1].equals("up"))
					movement = Action.MOVE_UP;
				else if (motions[1].equals("down"))
					movement = Action.MOVE_DOWN;
				}
			else {
				int Hmove = 0;
				int Vmove = 0;
				
				if(motions[0].equals("east"))
					Hmove = Action.MOVE_EAST;
				else if (motions[0].equals("west"))
					Hmove = Action.MOVE_WEST;
				
				if(motions[1].equals("up"))
					Vmove = Action.MOVE_UP;
				else if (motions[1].equals("down"))
					Vmove = Action.MOVE_DOWN;
				
				movement = Hmove|Vmove;
			}
		}
		
		return new Action(birdNum, Haction, Vaction, movement);
	}
	
	public static Vector<Action> getFlightPattern(int pattern) {
		if(flight == null) {			
			flight = new Vector<Action>();
			
			for(int i = 0; i < flightRecords[pattern].length; i++) {
				flight.add(stringToAction(flightRecords[pattern][i]));
			}
		}
		return flight;
	}
	
	public static final String[][] flightRecords = new String[][]
			{
		{
			"(0) A A west/up",
			"(0) A K west/up",
			"(0) A S west",
			"(0) K A west/up",
			"(0) K K west/up",
			"(0) K S west",
			"(0) S A /up",
			"(0) S K /up",
			"(0) S S",
			"(0) A A west/down",
			"(0) A K west/down",
			"(0) K A west/down",
			"(0) K K west/down",
			"(0) S A /down",
			"(0) S K /down",
			"(0) A A east/up",
			"(0) A K east/up",
			"(0) A S east",
			"(0) K A east/up",
			"(0) K K east/up",
			"(0) K S east",
			"(0) A A east/down",
			"(0) A K east/down",
			"(0) K A east/down",
			"(0) K K east/down" 
		},
		{
			"(0) A S east",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A A east/down",
			"(0) A S east",
			"(0) A S east",
			"(0) S A /up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) S A /up",
			"(0) S S",
			"(0) A A east/down",
			"(0) S A /down",
			"(0) A S east",
			"(0) S A /up",
			"(0) S S",
			"(0) A S west",
			"(0) S S",
			"(0) A S east",
			"(0) K S east",
			"(0) A A east/up",
			"(0) A S east",
			"(0) A S east",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/up",
			"(0) A S east",
			"(0) A S east",
			"(0) A A east/up",
			"(0) S A /up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) K A east/up",
			"(0) A S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) A S east",
			"(0) A A east/down",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) A A east/down",
			"(0) S S",
			"(0) S A /down",
			"(0) S A /down",
			"(0) S K /down",
			"(0) A A west/down",
			"(0) K A west/down",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) A K west/down",
			"(0) A A west/down",
			"(0) A K west/down",
			"(0) A K west/down",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) S S",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/up",
			"(0) K S east",
			"(0) S A /up",
			"(0) S S",
			"(0) S S",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S S",
			"(0) A A west/up",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) S S",
			"(0) A S west",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) S S",
			"(0) S A /down",
			"(0) A S west",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S S",
			"(0) S S",
			"(0) S A /down",
			"(0) A A west/down",
			"(0) A S west",
			"(0) A A west/down",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A S west",
			"(0) A A west/down",
			"(0) S S",
			"(0) S A /up",
			"(0) S A /up",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) S S",
			"(0) S A /down",
			"(0) A S east",
			"(0) A S east",
			"(0) S A /up",
			"(0) A A west/up",
			"(0) S S",
			"(0) A A east/down",
			"(0) K S east",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) S S",
			"(0) S S",
			"(0) A S west",
			"(0) A S west",
			"(0) A S west",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A S west",
			"(0) S S",
			"(0) S S",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) S A /up",
			"(0) S S",
			"(0) A S east",
			"(0) A S east",
			"(0) A S east",
			"(0) S A /down",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A A east/down",
			"(0) S S",
			"(0) S S",
			"(0) A A west/down",
			"(0) S S",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/up",
			"(0) A S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/up",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K A east/up",
			"(0) K A east/up",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A A east/down",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K A east/down",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/up",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A A east/down",
			"(0) S A /down",
			"(0) A S west",
			"(0) A A west/down",
			"(0) A S west",
			"(0) S S",
			"(0) S S",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S S",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S A /up",
			"(0) S S",
			"(0) S A /down",
			"(0) A S east",
			"(0) S S",
			"(0) S S",
			"(0) A S west",
			"(0) A S west",
			"(0) K A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A K west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S S",
			"(0) A A east/up",
			"(0) S A /up",
			"(0) S S",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) A S west",
			"(0) A S west",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) A S east",
			"(0) S A /down",
			"(0) S A /down",
			"(0) S S",
			"(0) A S west",
			"(0) A S west",
			"(0) S A /down",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S A /up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) S A /up",
			"(0) S S",
			"(0) S A /down",
			"(0) A A west/down",
			"(0) A S west",
			"(0) S A /up",
			"(0) S S",
			"(0) S S",
			"(0) A A east/down",
			"(0) A A east/down",
			"(0) A A east/down",
			"(0) S S",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A K east/up",
			"(0) A S east",
			"(0) A A east/up",
			"(0) K S east",
			"(0) K A east/down",
			"(0) K A east/down",
			"(0) K S east",
			"(0) K S east",
			"(0) K A east/up",
			"(0) K S east",
			"(0) A S east",
			"(0) K S east",
			"(0) A S east",
			"(0) A A east/up",
			"(0) S S",
			"(0) A S west",
			"(0) S A /up",
			"(0) S A /up",
			"(0) S A /up",
			"(0) S A /up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) K K west/up",
			"(0) K A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) K A west/up",
			"(0) A S west",
			"(0) A A west/down",
			"(0) S S",
			"(0) A A east/down",
			"(0) S A /down",
			"(0) S S",
			"(0) A A east/down",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/up",
			"(0) S S",
			"(0) A A east/up",
			"(0) S S",
			"(0) A A east/up",
			"(0) A S east",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) S S",
			"(0) A S east",
			"(0) S A /down",
			"(0) S A /down",
			"(0) A S west",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) A A east/up",
			"(0) S S",
			"(0) S S",
			"(0) A S east",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S S",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) A A west/down",
			"(0) S S",
			"(0) A A east/down",
			"(0) A S east",
			"(0) S S",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) K A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) K A west/up",
			"(0) A A west/up",
			"(0) A A west/up",
			"(0) A S west",
			"(0) S S",
			"(0) A A west/up",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A S west",
			"(0) A A west/down",
			"(0) A S west",
			"(0) A S west",
			"(0) A A west/up",
			"(0) A S west",
			"(0) S A /up",
			"(0) A A east/up",
			"(0) A S east",
			"(0) S S",
			"(0) S A /down",
			"(0) S S",
			"(0) A A west/down",
			"(0) S S",
			"(0) A S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) A S east",
			"(0) A S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east",
			"(0) K S east"
		}
			};
}
